version: '3.8'

services:
  # Frontend Only
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: honda-plus-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    environment:
      - NODE_ENV=development
    networks:
      - honda-plus-network
    restart: unless-stopped

  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: honda-plus-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=hondaplus2024
      - MONGO_INITDB_DATABASE=honda-plus
    volumes:
      - mongodb_data:/data/db
      - ./docker/mongodb/init:/docker-entrypoint-initdb.d
    networks:
      - honda-plus-network
    restart: unless-stopped
    command: mongod --auth

  # Redis Cache
  redis:
    image: redis:7.2-alpine
    container_name: honda-plus-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - honda-plus-network
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass hondaplus2024

  # MongoDB Express (Development only)
  mongo-express:
    image: mongo-express:latest
    container_name: honda-plus-mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=hondaplus2024
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=hondaplus2024
    depends_on:
      - mongodb
    networks:
      - honda-plus-network
    restart: unless-stopped

  # Redis Commander
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: honda-plus-redis-commander
    ports:
      - "8082:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379:0:hondaplus2024
    depends_on:
      - redis
    networks:
      - honda-plus-network
    restart: unless-stopped

volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local

networks:
  honda-plus-network:
    driver: bridge